site_name: Arista with Ansible
pages:
  - Home: 'index.md'
  - Installation: INSTALL.md
  - Modules:
      - eos_command: 'COLLECTING_STATUS.md'
      - eos_config: 'EOS_CONFIG.md'
      - templating: 'JINJA_YAML_STRUCTURES.md'
theme: readthedocs
